"use client";

import Link from "next/link";
import { FormEvent, ReactNode, useEffect, useState } from "react";
import AeroportoAutocomplete from "@/components/AeroportoAutocomplete";
import { adicionarRecente, alternarFavorita, BuscaSalva, listarFavoritas, listarRecentes, rotaFavorita } from "@/lib/flightSearchStorage";
import { ativarNotificacoesPush, precisaInstalarPWAnoIOS } from "@/lib/registrarPush";

type Voo = { id: string; preco: number; moeda: string; companhia: string; horarioPartida: string; horarioChegada: string; escalas: number; duracaoMinutos: number | null; linkGoogleFlights: string };
type PrecoDia = { data: string; preco: number | null };

function hojeLocal() { const agora = new Date(); return new Date(agora.getTime() - agora.getTimezoneOffset() * 60_000).toISOString().slice(0, 10); }
function formatarPreco(valor: number, moeda = "BRL") { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: moeda, maximumFractionDigits: 0 }).format(valor); }
function formatarHorario(valor: string) { const [, horario] = valor.split(" "); return horario || valor; }
function formatarData(data: string) { return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", timeZone: "UTC" }).format(new Date(`${data}T12:00:00Z`)).replace(" de ", " "); }
function textoEscalas(escalas: number) { return escalas === 0 ? "Voo direto" : `${escalas} escala${escalas > 1 ? "s" : ""}`; }
function Campo({ titulo, children }: { titulo: string; children: ReactNode }) { return <label className="rounded-xl border border-white/15 bg-white/[0.03] px-3 py-2"><span className="block text-[10px] text-white/45">{titulo}</span>{children}</label>; }

function CartaoVoo({ voo }: { voo: Voo }) {
  return <article className="rounded-2xl border border-white/10 bg-white/[0.04] p-4 shadow-xl shadow-black/10 transition hover:border-cyan-300/40"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-bold text-cyan-200">{voo.companhia}</p><p className="mt-2 text-2xl font-black tracking-tight text-white">{formatarHorario(voo.horarioPartida)} <span className="mx-2 text-cyan-300">→</span> {formatarHorario(voo.horarioChegada)}</p><p className="mt-1 text-xs text-white/55">{textoEscalas(voo.escalas)}{voo.duracaoMinutos ? ` · ${Math.floor(voo.duracaoMinutos / 60)}h ${voo.duracaoMinutos % 60}min` : ""}</p></div><div className="shrink-0 text-right"><p className="text-xl font-black text-white">{formatarPreco(voo.preco, voo.moeda)}</p><p className="text-[10px] text-white/45">total exibido</p></div></div><div className="mt-4 flex items-center justify-between gap-3 border-t border-white/10 pt-3"><p className="text-[10px] leading-relaxed text-white/40">Preço consultado em tempo real. Confirme disponibilidade antes de comprar.</p><a href={voo.linkGoogleFlights} target="_blank" rel="noopener noreferrer" className="shrink-0 rounded-lg bg-cyan-400 px-4 py-2 text-xs font-black text-slate-950 transition hover:bg-cyan-300">Ver no Google Flights ↗</a></div></article>;
}

export default function BuscaPassagens() {
  const hoje = hojeLocal(); const [origin, setOrigin] = useState("GYN"); const [destination, setDestination] = useState(""); const [outboundDate, setOutboundDate] = useState(""); const [returnDate, setReturnDate] = useState(""); const [adults, setAdults] = useState(1);
  const [voos, setVoos] = useState<Voo[]>([]); const [precos, setPrecos] = useState<PrecoDia[]>([]); const [buscando, setBuscando] = useState(false); const [buscandoPrecos, setBuscandoPrecos] = useState(false); const [erro, setErro] = useState(""); const [buscaRealizada, setBuscaRealizada] = useState(false);
  const [recentes, setRecentes] = useState<BuscaSalva[]>([]); const [favoritas, setFavoritas] = useState<BuscaSalva[]>([]);
  const [avisoPush, setAvisoPush] = useState(""); const [ativandoPush, setAtivandoPush] = useState(false); const [iosSemPwa, setIosSemPwa] = useState(false);
  useEffect(() => { queueMicrotask(() => { setRecentes(listarRecentes()); setFavoritas(listarFavoritas()); setIosSemPwa(precisaInstalarPWAnoIOS()); }); }, []);

  function preencher(busca: BuscaSalva) { setOrigin(busca.origin); setDestination(busca.destination); setOutboundDate(busca.outboundDate); setReturnDate(busca.returnDate); setAdults(busca.adults); }
  async function executarBusca(busca: BuscaSalva) {
    if (!busca.origin || !busca.destination || !busca.outboundDate) { setErro("Escolha a origem, o destino e a data de ida."); return; }
    preencher(busca); setBuscando(true); setBuscandoPrecos(true); setErro(""); setBuscaRealizada(true); setVoos([]); setPrecos([]);
    setRecentes(adicionarRecente(busca));
    const parametros = new URLSearchParams({ origin: busca.origin, destination: busca.destination, outbound_date: busca.outboundDate, adults: String(busca.adults) }); if (busca.returnDate) parametros.set("return_date", busca.returnDate);
    void fetch(`/api/calendario-precos?${parametros}`).then(async (resposta) => { const corpo = await resposta.json() as { precos?: PrecoDia[] }; if (resposta.ok) setPrecos(corpo.precos ?? []); }).finally(() => setBuscandoPrecos(false));
    try { const resposta = await fetch(`/api/busca-tempo-real?${parametros}`); const corpo = await resposta.json() as { voos?: Voo[]; error?: string }; if (!resposta.ok) throw new Error(corpo.error || "Não foi possível buscar os voos."); setVoos(corpo.voos ?? []); }
    catch (error) { setErro(error instanceof Error ? error.message : "Não foi possível buscar os voos."); } finally { setBuscando(false); }
  }
  function buscar(event: FormEvent<HTMLFormElement>) { event.preventDefault(); void executarBusca({ origin, destination, outboundDate, returnDate, adults, salvaEm: Date.now() }); }
  function favoritar() { if (!origin || !destination) return; setFavoritas(alternarFavorita({ origin, destination, outboundDate, returnDate, adults, salvaEm: Date.now() })); }
  async function ativarPush() { setAtivandoPush(true); setAvisoPush(""); try { await ativarNotificacoesPush(); setAvisoPush("Notificações ativadas neste dispositivo."); } catch (error) { setAvisoPush(error instanceof Error ? error.message : "Não foi possível ativar as notificações."); } finally { setAtivandoPush(false); } }
  const buscaAtual = { origin, destination, outboundDate, returnDate, adults, salvaEm: 0 }; const favorita = rotaFavorita(buscaAtual, favoritas); const classeInput = "mt-1 w-full bg-transparent text-base font-bold text-white outline-none [color-scheme:dark] placeholder:text-white/25";

  return <div className="min-h-dvh bg-[radial-gradient(circle_at_85%_0%,rgba(14,165,233,0.25),transparent_28%),linear-gradient(160deg,#061b31_0%,#020617_58%,#05192b_100%)] px-4 pb-12 pt-10 text-white sm:px-6"><div className="mx-auto max-w-4xl">
    <Link href="/passagens" className="inline-flex h-9 w-9 items-center justify-center rounded-full bg-white/10 text-2xl text-white/80" aria-label="Voltar para as promoções">‹</Link><p className="mt-5 text-sm font-semibold uppercase tracking-[0.22em] text-cyan-300">Busca em tempo real</p><h1 className="mt-2 text-3xl font-black tracking-tight">Encontre sua passagem</h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-white/65">Pesquise preços atuais do Google Flights por rota, data e número de passageiros.</p>
    {(favoritas.length > 0 || recentes.length > 0) && <section className="mt-5 space-y-3">{favoritas.length > 0 && <div><p className="mb-2 text-[10px] font-bold uppercase tracking-widest text-amber-200">★ Rotas favoritas</p><div className="flex gap-2 overflow-x-auto pb-1">{favoritas.map((item) => <button key={`${item.origin}-${item.destination}`} onClick={() => void executarBusca({ ...item, salvaEm: Date.now() })} className="shrink-0 rounded-full border border-amber-300/20 bg-amber-300/10 px-3 py-2 text-xs font-bold text-amber-100">{item.origin} → {item.destination}</button>)}</div></div>}{recentes.length > 0 && <div><p className="mb-2 text-[10px] font-bold uppercase tracking-widest text-white/45">Buscas recentes</p><div className="flex gap-2 overflow-x-auto pb-1">{recentes.map((item, indice) => <button key={`${item.origin}-${item.destination}-${item.outboundDate}-${indice}`} onClick={() => void executarBusca({ ...item, salvaEm: Date.now() })} className="shrink-0 rounded-full border border-white/10 bg-white/[0.04] px-3 py-2 text-xs text-white/75">{item.origin} → {item.destination} · {formatarData(item.outboundDate)}</button>)}</div></div>}</section>}
    <section className="mt-6 rounded-[1.5rem] border border-cyan-300/15 bg-slate-950/55 p-4 shadow-2xl shadow-cyan-950/20 backdrop-blur sm:p-5"><form onSubmit={buscar} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><AeroportoAutocomplete key={`origem-${origin}`} titulo="Origem" value={origin} onChange={setOrigin} excluir={destination} /><AeroportoAutocomplete key={`destino-${destination}`} titulo="Destino" value={destination} onChange={setDestination} excluir={origin} /><Campo titulo="Data de ida"><input type="date" value={outboundDate} onChange={(event) => setOutboundDate(event.target.value)} min={hoje} required className={classeInput} /></Campo><Campo titulo="Data de volta (opcional)"><input type="date" value={returnDate} onChange={(event) => setReturnDate(event.target.value)} min={outboundDate || hoje} className={classeInput} /></Campo><Campo titulo="Passageiros"><input type="number" value={adults} onChange={(event) => setAdults(Number(event.target.value))} min={1} max={9} required className={classeInput} /></Campo><button type="button" onClick={favoritar} disabled={!origin || !destination} className="rounded-xl border border-amber-300/25 bg-amber-300/10 px-4 py-3 text-sm font-bold text-amber-100 disabled:opacity-30 lg:col-span-1">{favorita ? "★ Favorita" : "☆ Favoritar rota"}</button><button type="submit" disabled={buscando} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white transition hover:bg-blue-500 disabled:cursor-wait disabled:opacity-60 sm:col-span-2 lg:col-span-4">{buscando ? "Buscando voos…" : "Buscar"}</button></form></section>
    <section className="mt-4 rounded-xl border border-white/10 bg-white/[0.04] p-3">{iosSemPwa ? <p className="text-xs leading-relaxed text-amber-100">No iPhone, adicione este app à Tela de Início pra receber notificações.</p> : <button type="button" onClick={() => void ativarPush()} disabled={ativandoPush} className="w-full rounded-lg border border-cyan-300/25 bg-cyan-300/10 px-4 py-3 text-sm font-bold text-cyan-100 disabled:opacity-60">{ativandoPush ? "Ativando…" : "🔔 Ativar alertas por notificação"}</button>}{avisoPush && <p role="status" className="mt-2 text-xs text-white/65">{avisoPush}</p>}</section>
    {erro && <p role="alert" className="mt-4 rounded-xl border border-red-400/15 bg-red-500/10 px-4 py-3 text-sm text-red-200">{erro}</p>}
    {(buscandoPrecos || precos.length > 0) && <section className="mt-5"><div className="mb-2 flex items-center justify-between"><p className="text-xs font-bold text-white/70">Compare datas próximas</p>{buscandoPrecos && <span className="text-[10px] text-cyan-200">Consultando…</span>}</div><div className="flex gap-2 overflow-x-auto pb-2">{precos.map((item) => <button key={item.data} disabled={item.preco === null || buscando} onClick={() => void executarBusca({ ...buscaAtual, outboundDate: item.data, salvaEm: Date.now() })} className={`min-w-24 shrink-0 rounded-xl border px-3 py-3 text-center ${item.data === outboundDate ? "border-cyan-300 bg-cyan-300/15" : "border-white/10 bg-white/[0.04]"}`}><span className="block text-xs text-white/55">{formatarData(item.data)}</span><span className="mt-1 block text-sm font-black text-white">{item.preco === null ? "—" : formatarPreco(item.preco)}</span></button>)}</div></section>}
    <section className="pt-6" aria-live="polite" aria-busy={buscando}>{buscando && <p className="text-sm font-semibold text-cyan-200">Consultando preços no Google Flights…</p>}{!buscando && buscaRealizada && !erro && <p className="mb-3 text-xs font-semibold text-cyan-200">{voos.length} {voos.length === 1 ? "voo encontrado" : "voos encontrados"}</p>}<div className="space-y-3">{voos.map((voo) => <CartaoVoo key={voo.id} voo={voo} />)}</div>{!buscando && buscaRealizada && !erro && voos.length === 0 && <p className="rounded-xl border border-white/10 bg-white/[0.04] p-4 text-sm text-white/60">Nenhum voo foi encontrado para essa combinação. Tente outras datas ou aeroportos.</p>}</section>
  </div></div>;
}
