"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Alerta = { id: string; origin: string; destination: string; outbound_date: string; return_date: string | null; adults: number; preco_alvo: number; ativo: boolean; created_at: string };
function hojeLocal() { const agora = new Date(); return new Date(agora.getTime() - agora.getTimezoneOffset() * 60_000).toISOString().slice(0, 10); }
function data(dataIso: string) { return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${dataIso}T12:00:00Z`)); }
function preco(valor: number) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(valor); }

export default function MeusAlertas() {
  const [alertas, setAlertas] = useState<Alerta[]>([]); const [token, setToken] = useState(""); const [carregando, setCarregando] = useState(true); const [erro, setErro] = useState(""); const [removendo, setRemovendo] = useState("");
  useEffect(() => { void supabase.auth.getSession().then(async ({ data: sessao }) => { const accessToken = sessao.session?.access_token; if (!accessToken) { setErro("Entre na sua conta para ver seus alertas."); setCarregando(false); return; } setToken(accessToken); try { const resposta = await fetch("/api/alertas", { headers: { Authorization: `Bearer ${accessToken}` }, cache: "no-store" }); const corpo = await resposta.json() as { alertas?: Alerta[]; error?: string }; if (!resposta.ok) throw new Error(corpo.error); setAlertas(corpo.alertas ?? []); } catch (error) { setErro(error instanceof Error ? error.message : "Não foi possível carregar seus alertas."); } finally { setCarregando(false); } }); }, []);
  async function remover(id: string) { setRemovendo(id); setErro(""); try { const resposta = await fetch(`/api/alertas?id=${encodeURIComponent(id)}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } }); const corpo = await resposta.json() as { error?: string }; if (!resposta.ok) throw new Error(corpo.error); setAlertas((atuais) => atuais.filter((item) => item.id !== id)); } catch (error) { setErro(error instanceof Error ? error.message : "Não foi possível remover o alerta."); } finally { setRemovendo(""); } }
  const hoje = hojeLocal();
  return <main className="min-h-dvh bg-[radial-gradient(circle_at_85%_0%,rgba(14,165,233,0.25),transparent_28%),linear-gradient(160deg,#061b31_0%,#020617_58%,#05192b_100%)] px-4 pb-16 pt-10 text-white sm:px-6"><div className="mx-auto max-w-3xl"><Link href="/passagens" className="inline-flex h-9 w-9 items-center justify-center rounded-full bg-white/10 text-2xl text-white/80" aria-label="Voltar para passagens">‹</Link><p className="mt-5 text-sm font-semibold uppercase tracking-[0.22em] text-cyan-300">Alertas de preço</p><h1 className="mt-2 text-3xl font-black tracking-tight">Meus alertas</h1><p className="mt-2 text-sm text-white/60">Acompanhe suas rotas e remova alertas que não deseja mais receber.</p>{erro && <p role="alert" className="mt-5 rounded-xl border border-red-400/20 bg-red-500/10 p-3 text-sm text-red-200">{erro}</p>}<section className="mt-6 space-y-3" aria-busy={carregando}>{carregando && <p className="text-sm text-cyan-200">Carregando alertas…</p>}{!carregando && !erro && alertas.length === 0 && <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 text-center"><p className="text-sm text-white/60">Você ainda não criou alertas de preço.</p><Link href="/buscar-passagens" className="mt-4 inline-flex rounded-xl bg-cyan-400 px-4 py-3 text-sm font-black text-slate-950">Buscar passagens</Link></div>}{alertas.map((alerta) => { const expirado = alerta.outbound_date < hoje; return <article key={alerta.id} className={`rounded-2xl border p-4 ${expirado ? "border-white/10 bg-white/[0.025] opacity-75" : "border-cyan-300/20 bg-white/[0.05]"}`}><div className="flex items-start justify-between gap-3"><div><span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-black uppercase tracking-wider ${expirado ? "bg-slate-500/20 text-slate-300" : "bg-emerald-400/15 text-emerald-300"}`}>{expirado ? "Expirado" : "Ativo"}</span><h2 className="mt-2 text-2xl font-black">{alerta.origin} <span className="text-cyan-300">→</span> {alerta.destination}</h2><p className="mt-1 text-xs text-white/55">Ida: {data(alerta.outbound_date)}{alerta.return_date ? ` · Volta: ${data(alerta.return_date)}` : " · Só ida"}</p></div><div className="text-right"><p className="text-[10px] uppercase tracking-wide text-white/40">Preço máximo</p><p className="mt-1 text-lg font-black">{preco(Number(alerta.preco_alvo))}</p></div></div><button type="button" onClick={() => void remover(alerta.id)} disabled={removendo === alerta.id} className="mt-4 w-full rounded-xl border border-red-300/20 bg-red-400/10 px-4 py-3 text-xs font-bold text-red-200 disabled:opacity-50">{removendo === alerta.id ? "Removendo…" : "Remover alerta"}</button></article>; })}</section></div></main>;
}
