"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Oferta = { id: string; origem: string; destino: string; preco: number; moeda: string; partida: string; volta: string | null; encontradaEm: string; link: string };

function formatarPreco(valor: number, moeda: string) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: moeda }).format(valor); }
function formatarData(data: string) { return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${data}T12:00:00`)); }

function NavegacaoPassagens() {
  return <nav className="fixed inset-x-0 bottom-0 z-40 mx-auto w-full border-t border-white/10 bg-[#020617]/95 px-3 pb-[calc(env(safe-area-inset-bottom)+14px)] pt-3 shadow-[0_-16px_40px_rgba(0,0,0,0.35)] backdrop-blur sm:max-w-sm"><div className="grid grid-cols-5 items-end gap-1 text-[11px] font-semibold"><Link href="/buscar-passagens" className="flex min-w-0 flex-col items-center gap-1 text-cyan-300"><span className="text-2xl leading-none">✈</span><span className="truncate">Passagens</span></Link><Link href="/cabine" className="flex min-w-0 flex-col items-center gap-1 text-white/45"><span className="text-2xl leading-none">▶</span><span className="truncate">Cabine</span></Link><Link href="/minha-viagem" className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-white text-3xl text-black shadow-lg" aria-label="Início">+</Link><Link href="/roteiro" className="flex min-w-0 flex-col items-center gap-1 text-white/45"><span className="text-2xl leading-none">🧭</span><span className="truncate">Roteiro</span></Link><Link href="/minha-viagem" className="flex min-w-0 flex-col items-center gap-1 text-white/45"><span className="text-2xl leading-none">🗺</span><span className="truncate">Destinos</span></Link></div></nav>;
}

function CartaoOferta({ oferta, referencia }: { oferta: Oferta; referencia: number }) {
  const desconto = referencia > oferta.preco ? Math.round((1 - oferta.preco / referencia) * 100) : 0;
  return <article className="rounded-2xl border border-white/10 bg-white/[0.04] p-4 shadow-xl shadow-black/10 transition hover:border-cyan-300/40"><div className="flex items-start justify-between gap-3"><div>{desconto > 0 && <span className="inline-flex rounded-full bg-emerald-400/15 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-emerald-300">{desconto}% abaixo da mais alta</span>}<p className="mt-2 text-2xl font-black tracking-tight text-white">{oferta.origem} <span className="mx-1 text-cyan-300">→</span> {oferta.destino}</p><p className="mt-1 text-xs text-white/55">Ida: {formatarData(oferta.partida)}{oferta.volta ? ` · Volta: ${formatarData(oferta.volta)}` : " · Só ida"}</p></div><div className="shrink-0 text-right"><p className="text-xl font-black text-white">{formatarPreco(oferta.preco, oferta.moeda)}</p><p className="text-[10px] text-white/45">por pessoa</p></div></div><div className="mt-4 flex items-center justify-between gap-3 border-t border-white/10 pt-3"><p className="text-[10px] leading-relaxed text-white/40">Preço encontrado recentemente pela Travelpayouts</p><a href={oferta.link} target="_blank" rel="noopener noreferrer" className="shrink-0 rounded-lg bg-cyan-400 px-4 py-2 text-xs font-black text-slate-950 transition hover:bg-cyan-300">Ver oferta ↗</a></div></article>;
}

export default function Passagens() {
  const [origem, setOrigem] = useState("GYN"); const [ofertas, setOfertas] = useState<Oferta[]>([]); const [buscando, setBuscando] = useState(true); const [erro, setErro] = useState(""); const [aviso, setAviso] = useState("");
  const carregar = useCallback(async (codigo: string) => { setBuscando(true); setErro(""); try { const resposta = await fetch(`/api/buscar-passagens?origem=${encodeURIComponent(codigo)}`); const corpo = (await resposta.json()) as { ofertas?: Oferta[]; aviso?: string; error?: string }; if (!resposta.ok) throw new Error(corpo.error || "Não foi possível carregar as ofertas."); setOfertas(corpo.ofertas ?? []); setAviso(corpo.aviso ?? ""); } catch (error) { setOfertas([]); setErro(error instanceof Error ? error.message : "Não foi possível carregar as ofertas."); } finally { setBuscando(false); } }, []);
  function atualizar(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const codigo = origem.trim().toUpperCase(); setOrigem(codigo); void carregar(codigo); }
  useEffect(() => { void Promise.resolve().then(() => carregar("GYN")); }, [carregar]);
  const maiorPreco = useMemo(() => Math.max(...ofertas.map((oferta) => oferta.preco), 0), [ofertas]);
  return <div className="min-h-dvh bg-[radial-gradient(circle_at_85%_0%,rgba(14,165,233,0.25),transparent_28%),linear-gradient(160deg,#061b31_0%,#020617_58%,#05192b_100%)] pb-28 text-white"><header className="px-5 pb-5 pt-10"><Link href="/minha-viagem" className="inline-flex h-9 w-9 items-center justify-center rounded-full bg-white/10 text-2xl text-white/80" aria-label="Voltar">‹</Link><p className="mt-5 text-sm font-semibold uppercase tracking-[0.22em] text-cyan-300">Ofertas encontradas recentemente</p><h1 className="mt-2 text-3xl font-black tracking-tight">Passagens baratas</h1><p className="mt-2 text-sm leading-relaxed text-white/65">Escolha uma promoção ou faça uma pesquisa com rota e datas livres.</p></header><section className="mx-4 rounded-[1.5rem] border border-cyan-300/15 bg-slate-950/55 p-4 shadow-2xl shadow-cyan-950/20 backdrop-blur"><form onSubmit={atualizar} className="flex gap-3"><label className="min-w-0 flex-1 rounded-xl border border-white/15 bg-white/[0.03] px-3 py-2"><span className="block text-[10px] text-white/45">Origem (IATA)</span><input value={origem} onChange={(event) => setOrigem(event.target.value.toUpperCase())} maxLength={3} pattern="[A-Za-z]{3}" required aria-label="Código IATA de origem" className="mt-1 w-full bg-transparent text-lg font-black tracking-widest text-white outline-none" /></label><button type="submit" disabled={buscando} className="rounded-xl bg-blue-600 px-4 text-xs font-black text-white transition hover:bg-blue-500 disabled:opacity-60">{buscando ? "Buscando…" : "Atualizar"}</button></form><Link href="/buscar-passagens" className="mt-3 flex w-full items-center justify-center rounded-xl border border-cyan-300/30 bg-cyan-300/10 px-4 py-3 text-xs font-bold text-cyan-100 transition hover:bg-cyan-300/20">⌕ Buscar por conta própria</Link></section>{erro && <p className="mx-4 mt-4 rounded-xl border border-red-400/15 bg-red-500/10 px-4 py-3 text-xs leading-relaxed text-red-200">{erro}</p>}{aviso && !erro && <p className="mx-4 mt-4 rounded-xl border border-amber-300/15 bg-amber-300/[0.07] px-4 py-3 text-xs leading-relaxed text-amber-100">{aviso}</p>}<section className="px-4 pt-5"><p className="mb-3 text-xs font-semibold text-cyan-200">{buscando ? "Atualizando promoções…" : `${ofertas.length} ofertas saindo de ${origem}`}</p><div className="space-y-3">{ofertas.map((oferta) => <CartaoOferta key={oferta.id} oferta={oferta} referencia={maiorPreco} />)}</div>{!buscando && !erro && ofertas.length === 0 && <p className="rounded-xl border border-white/10 bg-white/[0.04] p-4 text-sm text-white/60">Nenhuma oferta recente foi encontrada para esta origem. Tente outro aeroporto.</p>}</section><NavegacaoPassagens /></div>;
}
